### ISSUE TITLE
Develop comprehensive test strategy

### ISSUE THREAD

**Issue by ccjoel** [jataware/dojo#110]
- [ ] UI E2E testing
- [ ] Unit tests for API
- [ ] Unit tests for processors/RQ
- [ ] Elwood testing
- [ ] GH Action integrations for running simpler unit tests

Options may include:
* Cypress
* Puppeteer + Chrome recording
* simpler unittests
* spinning up test environment (periodically)
* etc etc etc

**Comment by ccjoel** [comment]
Re: Stories
[DOjo E2E Test Stories](https://docs.google.com/document/d/1aYM_EMjQifQM0_ZMriY7fQ3tRs9wxkJ9uyAY8eq4ojE/edit?usp=sharing)

Re: Recording- seems cypress has similar functionality. Evaluating.

**Comment by brandomr** [comment]
Tag me for sections in that doc that you have questions!

**Comment by ccjoel** [comment]
Pending: Need to disable E2E tests on github on the open E2E tests PR. Somehow the config is not kicking in.

Update: done.

**Comment by ccjoel** [comment]
Merged the big Cypress E2E PR with the bulk of my changes, setup, seeding, etc. I want to go through it with Adam first, maybe improve or think/address some quality-of-life improvements, then run all of it again with Powell (for example) for us to author a test together, then run it all on whatever final version with Brandon. I don't think that any doc/guide will outright make any other developer an expert on cypress e2e tests if we don't pair first to get a feel of all of it. It's a lot to learn.
