### ISSUE TITLE
[Regression] Dataset Update Metadata: Unable to edit (click) multipart fields

### ISSUE THREAD

**Issue by ccjoel** [jataware/dojo#127]
Example unable to click the `Edit` button for Latitude,Longitude and country/build-a-geo fields to edit description, metadata. When clicking the button, it does nothing (only for multipart edit buttons)

![Screenshot from 2023-07-17 16-43-40](https://github.com/jataware/dojo/assets/1967061/d27e8c59-5434-48bb-9856-d8da0b35029d)

**Comment by brandomr** [comment]
I'll verify this
