### ISSUE TITLE
Upgrade React and components

### ISSUE THREAD

**Issue by brandomr** [jataware/dojo#137]
Part of overall desire to harden systems and keep them up to speed/easy to maintain. Includes:

- [ ] Upgrade React
- [x] Upgrade Material UI
- [x] Upgrade Cypress

**Comment by adamgilg** [comment]
@ccjoel is working on upgrading Cypress with https://github.com/jataware/dojo/pull/132
I'm working on upgrading MUI and React.

07/31/23 update: MUI Upgrade is in progress. Library is updated and all imports are renamed, and I'm about halfway through the migration scripts (codemods), which only somewhat work. Once these scripts are done the remaining todos are:

- [x] Datepickers
    - [x] disable all existing keyboarddatepickers
    - [x] change them all to regular datepickers
- [x] remove clsx, replace with new format
- [x] go through two pages of MUI docs on breaking changes and make fixes
- [x] upgrade data-grid
- [x] deal with material-ui-formik-components, which will most likely not work with v5
    - [x] replace with a new library or write our own if mui-f-c doesn't work

08/21/23 update: Much of the formal upgrade work is done. The pickers and mui-formik-components  still need to be upgraded. Then there are a number of small visual changes from the upgrade, many of which need addressing. I'm also compiling a list of things that I've had to disable/put off fixing within the scope of the upgrade task. I'll make an issue with this list soon.

**Comment by adamgilg** [comment]
PR now up for upgrading React: https://github.com/jataware/dojo/pull/166
