### ISSUE TITLE
Document search enhancements and bugfixes

### ISSUE THREAD

**Issue by brandomr** [jataware/dojo#153]
- [x] search by document title
- [x] `GET /documents` should not return those that are still being processed
- [x] Document sort by `creation date` has a bug
- [x] Sort alphabetical problems (ie set to case insensitive)
- [x] paragraph id bug

See: https://darpa-world-modelers.slack.com/archives/C054VJF5894/p1691760546237849

**Comment by ccjoel** [comment]
#154 addresses "Search by document title" and document sort alphabetical/lowercase issue.

**Comment by ccjoel** [comment]
Addressed by #155, #156 as well (supporting scripts).
