### ISSUE TITLE
Newly registered dataset not sent to Causemos

### ISSUE THREAD

**Issue by bagoodman** [jataware/dojo#180]
The Paler Drought Severity Index (PDSI) - Sample Set of Countries - 2020-2022 - Monthly dataset registered in Dojo on 10/12/2023 is not showing up in Causemos, https://causemos-analyst.dojo-modeling.com/dataset_summary?dataset=a3413f5f-bb78-451b-bf58-b62e089f1c5f.

**Comment by brandomr** [comment]
Duplicate of #181
