### ISSUE TITLE
Palmer Drought Severity Index (PDSI) - Sample Set of Countries - 2020-2022 - Monthly never got to Causemos

### ISSUE THREAD

**Issue by bagoodman** [jataware/dojo#181]
The registered dataset, Palmer Drought Severity Index (PDSI) - Sample Set of Countries - 2020-2022 - Monthly, never got to Causemos: https://causemos-analyst.dojo-modeling.com/dataset_summary?dataset=a3413f5f-bb78-451b-bf58-b62e089f1c5f

Can it be resent? Thanks. -Brad

**Comment by brandomr** [comment]
https://app.causemos.ai/app/#/dataset/a3413f5f-bb78-451b-bf58-b62e089f1c5f/datasetOverview

its in processing now
