### ISSUE TITLE
Transform & Manage Data claiming need to adjust geospatial and temporal resolutions when shouldn't be doing that

### ISSUE THREAD

**Issue by bagoodman** [jataware/dojo#191]
A database of overseas military bases that has only the year 2020 for all entries and then lat/long for the locations of the military bases is bringing up the need to adjust the geospatial and temporal resolutions (which it should not be doing) and this causes an error during database registration (https://causemos-analyst.dojo-modeling.com/datasets/register/transform/3bcd2b87-1aa5-4897-bfc5-eb6af1b93bac?filename=raw_data.xlsx).  I will upload the dataset in Slack.

**Comment by brandomr** [comment]
@bagoodman this is addressed by https://github.com/jataware/dojo/pull/196 which we're testing and will deploy shortly.

**Comment by adamgilg** [comment]
@bagoodman we've deployed a fix for this that makes the geospatial and temporal resolution transformations not required. Let us know if you continue to run into issues after this fix.
