### ISSUE TITLE
Document Explorer - Full Text Shown is from a different document

### ISSUE THREAD

**Issue by bagoodman** [jataware/dojo#214]
I am finding that when I click on a document in the Document Explorer, it is showing the text under the Full Text portion from a DIFFERENT document and not the one uploaded. For example, the document 'The Carbon Brief Profile: China' has text from a completely different document shown under Full Text when you click on the document. NOTE: this is not true for all documents but newly uploaded ones.

**Comment by bagoodman** [comment]
In particular, look at the documents with Publisher 'CarbonBrief.' It also seems that maybe pieces of the correct document are being mixed in with some other documents under the Full Text portion. Note, when I did the document upload, I did multiple documents at once (dragging 10 documents into the Bulk Document Upload window), adding metadata to each of those documents. I think some of the document excerpts showing up under Full Text include some of the other documents during the bulk upload as well as at least one more document that was NOT included and had been uploaded sometime in the past.

**Comment by adamgilg** [comment]
I'm taking a look into this issue. It looks like the full text on most of the most recent batch is jumbled, if I'm parsing it correctly. 

This looks like it's combining text from a number of documents (and possibly metadata?):
![Screenshot 2023-12-19 at 11 51 46 AM](https://github.com/jataware/dojo/assets/2448578/9f464c42-8fb0-4959-aebe-fc3fe3826a24)

This is the issue you're referring to, correct? I'll continue digging into it further.

**Comment by bagoodman** [comment]
Yes, that is the issue that I am referring to. -Brad

From: adamgilg ***@***.***>
Date: Tuesday, December 19, 2023 at 11:54 AM
To: jataware/dojo ***@***.***>
Cc: Dr. Brad Goodman ***@***.***>, Author ***@***.***>
Subject: [EXT] Re: [jataware/dojo] Document Explorer - Full Text Shown is from a different document (Issue #214)
I'm taking a look into this issue. It looks like the full text on most of the most recent batch is jumbled, if I'm parsing it correctly. This looks like it's combining text from a number of documents (and possibly metadata?): Screenshot. 2023-12-19. at. 11. 51. 46. AM. png


I'm taking a look into this issue. It looks like the full text on most of the most recent batch is jumbled, if I'm parsing it correctly.

This looks like it's combining text from a number of documents (and possibly metadata?):
Screenshot.2023-12-19.at.11.51.46.AM.png (view on web)<https://github.com/jataware/dojo/assets/2448578/9f464c42-8fb0-4959-aebe-fc3fe3826a24>

This is the issue you're referring to, correct? I'll continue digging into it further.

**Comment by adamgilg** [comment]
Hi Brad,
We've figured out the cause of the problem and have a fix coming shortly. It was an incorrect Elasticsearch query matching too many document ids to a single document, so some documents would show paragraphs from several different documents all mixed together in sequence like: document ID `a` paragraph `0`, b-0, c-0, a-1, b-1, c-1, etc. 

This was happening whenever two document IDs had overlapping sections that ES decided were a close enough match. Sometimes a document had no matches other than its own correct paragraphs (and would thus have a correct `full text`), and sometimes it would have two, three, or possibly more matches, resulting in the jumbles you identified. 

Fix will be up with the next deployment. Thanks for your patience! 
- Adam

**Comment by bagoodman** [comment]
Thanks!

From: adamgilg ***@***.***>
Date: Wednesday, December 20, 2023 at 5:59 PM
To: jataware/dojo ***@***.***>
Cc: Dr. Brad Goodman ***@***.***>, Author ***@***.***>
Subject: [EXT] Re: [jataware/dojo] Document Explorer - Full Text Shown is from a different document (Issue #214)
Hi Brad, We've figured out the cause of the problem and have a fix coming shortly. It was an incorrect Elasticsearch query matching too many document ids to a single document, so some documents would show paragraphs from several different documents


Hi Brad,
We've figured out the cause of the problem and have a fix coming shortly. It was an incorrect Elasticsearch query matching too many document ids to a single document, so some documents would show paragraphs from several different documents all mixed together in sequence like: document ID a paragraph 0, b-0, c-0, a-1, b-1, c-1, etc.

This was happening whenever two document IDs had overlapping sections that ES decided were a close enough match. Sometimes a document had no matches other than its own correct paragraphs (and would thus have a correct full text), and sometimes it would have two, three, or possibly more matches, resulting in the jumbles you identified.

Fix will be up with the next deployment. Thanks for your patience!

  *   Adam
