### ISSUE TITLE
Fix for causemos actions not firing properly

### ISSUE THREAD

**Issue by mattprintz** [jataware/dojo#70]
Due to two refactors that were going on at the same time, some behavior from the api/src/causemos.py file didn't make it in to the plugin.
Namely, it looks like there are two functions that are causemos.py that are at issue. One is definitely an issue and the other one may or may not be and requires a little investigation. On top of that the plugin needs some reformatting.

The three issues are:
1. Converting the internal format to causemos format registration, primarily for parameters
2. Deprecating datasets
3. The causemos plugin still uses the "old" naming format for plugin functions such as `on_register_model(self, model)` instead of the new format `publish(self, data, type)`

For issue 1, the logic from `convert_to_causemose_format` function from src/causemos.py should be moved to the src/plugins/causemos.py file and should be executed for the data that is being sent to causemos before it is sent in the `on_register_` methods (not sure if needed for indicators, but definitely for models).
We should not be modifying the data that we store, just what gets sent to Causemos (in the notify_data deep copy).

For issue 2, we currently don't have a "deprecate" plugin hook. I don't recall if deprecate is a distinct step or if it is triggered by an `update` event. If it's triggered by an update on our side, then we probably want a `post_update` event that checks if deprecate changed and executes the code at that point.

For issue 3, we should mostly be able to just change the method names and signatures to fix. As the names don't exactly match, you will need to look at the code to confirm which step is the appropriate one, but I believe that:
* `on_register_model` and `on_register_indicator` both -> `publish(self, data, type)` with logic for branching based on type.
Note: (notify_causemos and submit_run are just helper functions and not triggers themselves so don't need to be changed)

**Comment by Sorrento110** [comment]
This issue has been fixed, the causemos plugin was updated to the new plugin paradigm.
